<?php

/**
 * Seed data for the default plan catalog. Admins can add, edit, or remove
 * plans and their feature matrix entirely from the admin panel afterwards —
 * this file only bootstraps a sensible starting catalog.
 */
return [

    'default_slug' => 'starter',

    'plans' => [
        [
            'name' => 'Starter',
            'slug' => 'starter',
            'description' => 'For a single site and the essentials.',
            'price_monthly' => 0,
            'price_yearly' => 0,
            'max_websites' => 1,
            'max_team_members' => 2,
            'max_scans_per_month' => 30,
            'scan_frequency' => 'daily',
            'ai_credits' => 0,
            'storage_mb' => 250,
            'sort_order' => 1,
            'features' => [
                'monitoring.core', 'performance.scans', 'seo.scans', 'security.scans',
                'reports.pdf', 'notifications.email',
            ],
        ],
        [
            'name' => 'Professional',
            'slug' => 'professional',
            'description' => 'For growing teams that need AI insight and more sites.',
            'price_monthly' => 2900,
            'price_yearly' => 29000,
            'max_websites' => 5,
            'max_team_members' => 10,
            'max_scans_per_month' => 300,
            'scan_frequency' => '1hr',
            'ai_credits' => 500,
            'storage_mb' => 2048,
            'sort_order' => 2,
            'features' => [
                'monitoring.core', 'performance.scans', 'seo.scans', 'security.scans', 'accessibility.scans',
                'ai.assistant', 'ai.report_summarization', 'ai.fix_generation',
                'reports.pdf', 'reports.csv', 'reports.scheduled',
                'notifications.email', 'notifications.slack', 'notifications.discord', 'notifications.webhook',
                'api.access',
            ],
        ],
        [
            'name' => 'Agency',
            'slug' => 'agency',
            'description' => 'For agencies managing many client sites, with pen testing.',
            'price_monthly' => 9900,
            'price_yearly' => 99000,
            'max_websites' => 25,
            'max_team_members' => 25,
            'max_scans_per_month' => 1500,
            'scan_frequency' => '30min',
            'ai_credits' => 2500,
            'storage_mb' => 10240,
            'sort_order' => 3,
            'features' => [
                'monitoring.core', 'performance.scans', 'seo.scans', 'security.scans', 'accessibility.scans',
                'ai.assistant', 'ai.report_summarization', 'ai.fix_generation',
                'pentest.module',
                'reports.pdf', 'reports.csv', 'reports.scheduled',
                'notifications.email', 'notifications.sms', 'notifications.slack', 'notifications.discord',
                'notifications.telegram', 'notifications.webhook',
                'api.access', 'white_label',
            ],
        ],
        [
            'name' => 'Enterprise',
            'slug' => 'enterprise',
            'description' => 'For large organizations with dedicated support needs.',
            'price_monthly' => 29900,
            'price_yearly' => 299000,
            'max_websites' => 100,
            'max_team_members' => 100,
            'max_scans_per_month' => 10000,
            'scan_frequency' => '15min',
            'ai_credits' => 10000,
            'storage_mb' => 51200,
            'sort_order' => 4,
            'features' => [
                'monitoring.core', 'performance.scans', 'seo.scans', 'security.scans', 'accessibility.scans',
                'ai.assistant', 'ai.report_summarization', 'ai.fix_generation',
                'pentest.module',
                'reports.pdf', 'reports.csv', 'reports.scheduled',
                'notifications.email', 'notifications.sms', 'notifications.slack', 'notifications.discord',
                'notifications.telegram', 'notifications.webhook',
                'api.access', 'white_label', 'priority_support',
            ],
        ],
        [
            'name' => 'Unlimited',
            'slug' => 'unlimited',
            'description' => 'Every feature, no caps.',
            'price_monthly' => 59900,
            'price_yearly' => 599000,
            'max_websites' => 999999,
            'max_team_members' => 999999,
            'max_scans_per_month' => 999999,
            'scan_frequency' => '5min',
            'ai_credits' => 999999,
            'storage_mb' => 999999,
            'sort_order' => 5,
            'features' => '*',
        ],
    ],
];
